AlkemyChallenge/Controllers/MatterController.cs
using AlkemyChallenge;
using AlkemyChallenge.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
namespace Alkemy.Controllers
{
    [Authorize]
    public class MatterController : Controller
    {
        // GET: Matters
        public ActionResult Index(string message = "")
        {
            List<ListMatters> List = new List<ListMatters>();
            List<ListMatters> ListOrder = new List<ListMatters>();
            bool List0 = false;
            using (UniversityEntities DB = new UniversityEntities())
            {
                var Inscriptioncount = DB.Inscription.ToList();
                List = (from m in DB.Matters
                        select new ListMatters
                        {
                            Id = m.Id,
                            Name_Matter = m.Name_Matter,
                            Schedule = m.Schedule,
                            Teacher = m.Id_Teacher,
                            Quota = m.Quota
                        }).ToList();
            }
            foreach (var ListC in List)
            {
                if (ListC.Quota != 0)
                {
                    List0 = true;
                    ListOrder.Add(new ListMatters() { Id = ListC.Id, Name_Matter = ListC.Name_Matter, Schedule = ListC.Schedule, Teacher = ListC.Teacher, Quota = ListC.Quota });
                }
            }
            string Usuario = User.Identity.Name;
            if (Usuario == "Administrador")
            {
                ListOrder = List.OrderBy(x => x.Name_Matter).ToList();
            }
            else if (List0)
            {
                ListOrder = ListOrder.OrderBy(x => x.Name_Matter).ToList();
            }
            else
            {
                ListOrder = List.OrderBy(x => x.Name_Matter).ToList();
            }
            ViewBag.Message = message;
            return View(ListOrder);
        }


        public ActionResult New()
        {
            return View();
        }

        [HttpPost]
        public ActionResult New(DataMatters EMatters)
        {
            bool Teacherexist = false;
            try
            {
                if (ModelState.IsValid)
                {
                    using (UniversityEntities DB = new UniversityEntities())
                    {
                        var EMatter = new Matters();
                        var Teachers = DB.Teachers.ToList();
                        EMatter.Name_Matter = EMatters.Name_Matter;
                        EMatter.Schedule = EMatters.Schedule;
                        foreach (var TeacherFind in Teachers)
                        {
                            if (TeacherFind.Id == EMatters.Id_Teacher)
                            {
                                EMatter.Id_Teacher = EMatters.Id_Teacher;
                                Teacherexist = true;
                            }
                        }
                        if (!Teacherexist)
                        {
                            return RedirectToAction("Index", new { message = "El Id del profesor no existe" });
                        }
                        if (EMatters.Quota<=0)
                        {
                            return RedirectToAction("Index", new { message = "El cupo debe ser mayor a 0" });
                        }
                        EMatter.Quota = EMatters.Quota;

                        DB.Matters.Add(EMatter);
                        DB.SaveChanges();
                    }
                    return Redirect("/Matter");
                }
                return View(EMatters);
            }
            catch (Exception ex)
            {

                throw new Exception(ex.Message);
            }
        }



        public ActionResult Edit(int Id)
        {
            DataMatters EMatters = new DataMatters();
            using (UniversityEntities DB = new UniversityEntities())
            {
                var EMatter= DB.Matters.Find(Id);
                EMatters.Name_Matter = EMatter.Name_Matter;
                EMatters.Schedule = EMatter.Schedule;
                EMatters.Id_Teacher = EMatter.Id_Teacher;
                EMatters.Quota = EMatter.Quota;
                EMatters.Id = EMatter.Id;
            }
            return View(EMatters);
        }
        [HttpPost]
        public ActionResult Edit(DataMatters EMatters)
        {
            bool Teacherexist= false;
            try
            {
                if (ModelState.IsValid)
                {
                    using (UniversityEntities DB = new UniversityEntities())
                    {
                        var EMatter = DB.Matters.Find(EMatters.Id);
                        var Teachers = DB.Teachers.ToList();
                        EMatter.Name_Matter = EMatters.Name_Matter;
                        EMatter.Schedule = EMatters.Schedule;
                        foreach (var TeacherFind in Teachers)
                        {
                            if (TeacherFind.Id == EMatters.Id_Teacher)
                            {
                                EMatter.Id_Teacher = EMatters.Id_Teacher;
                                Teacherexist = true;
                            }
                        }
                        if (!Teacherexist)
                        {
                            return RedirectToAction("Index", new { message = "El Id del profesor no existe" });
                        }
                        
                        if (EMatters.Quota <= 0)
                        {
                            return RedirectToAction("Index", new { message = "El cupo debe ser mayor a 0" });
                        }
                        EMatter.Quota = EMatters.Quota;
                        EMatter.Id = EMatters.Id;

                        DB.Entry(EMatter).State = System.Data.Entity.EntityState.Modified;
                        DB.SaveChanges();
                    }
                    return Redirect("/Matter");
                }
                return View(EMatters);
            }
            catch (Exception ex)
            {

                throw new Exception(ex.Message);
            }
        }


        [HttpGet]
        public ActionResult Delete(int Id)
        {
            using (UniversityEntities DB = new UniversityEntities())
            {

                var DMatter = DB.Matters.Find(Id);
                var DInscription = DB.Inscription.Find(Id);
                var Inscription = DB.Inscription.ToList();
                foreach (var dato in Inscription)
                {
                    if (dato.Id_Matter == Id)
                    {
                        DInscription = DB.Inscription.Find(dato.Id);
                        DB.Inscription.Remove(DInscription);
                    }
                }
                DB.Matters.Remove(DMatter);
                DB.SaveChanges();
            }
            return Redirect("/Matter");
        }
    }
}

AlkemyChallenge/Views/Matter/Edit.cshtml
@model AlkemyChallenge.Models.ViewModels.DataMatters
@{
    ViewBag.Title = "Editar";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Edit", "Matter", FormMethod.Post))
{
    string Usuario = User.Identity.Name;
    if (Usuario == "Administrador")
    {
        <div class="row">
            <div class="col-md-12">
                @Html.HiddenFor(m => m.Id)
                <div>
                    @Html.LabelFor(m => m.Name_Matter)
                    @Html.TextBoxFor(m => m.Name_Matter, "", new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Name_Matter, null)
                </div>
                <div>
                    @Html.LabelFor(m => m.Schedule)<br />
                    @Html.EditorFor(m => m.Schedule, "", new { @class = "form-control" })<br />
                    @Html.ValidationMessageFor(m => m.Schedule, null)
                </div>
                <div>
                    @Html.LabelFor(m => m.Id_Teacher)
                    @Html.TextBoxFor(m => m.Id_Teacher, "", new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Id_Teacher, null)
                </div>
                <div>
                    @Html.LabelFor(m => m.Quota)
                    @Html.TextBoxFor(m => m.Quota, "", new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Quota, null)
                </div>
                <div style="text-align:right">
                    <input value="Guardar" class="btn btn-success" type="Submit" />
                </div>
            </div>
        </div>
    }
    else
    {
        <label> NO TIENE LOS PERMISOS NECESARIOS</label>
        <a class="btn btn-danger" href="~/Matter">Volver</a>

    }
}

AlkemyChallenge/Views/Matter/Index.cshtml
@model List<AlkemyChallenge.Models.ViewModels.ListMatters>
@{
    ViewBag.Title = "Lista Materias";
}

<h2>@ViewBag.Title</h2>
<div class="row" style="text-align:right;padding:5px">
    @if (User.Identity.IsAuthenticated)
    {
        string Usuario = User.Identity.Name;
        if (Usuario == "Administrador")
        {
            <a href="~/Matter/New" class="btn btn-success">Nueva Materia</a>
        }
    }

</div>
<div class="row" style="text-align:right;padding:5px">
    <div class="container">
        @{
            if (!string.IsNullOrEmpty(ViewBag.Message))
            {
                <div class="alert alert-danger">@ViewBag.Message</div>
            }
        }
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <table class="table">
            <tr>
                <th>Materia</th>
                <th>Inicio</th>
                <th>Profesor</th>
                <th>Cupo</th>
                <th></th>
            </tr>
            @foreach (var Omatter in Model)
            {
                <tr>

                    <td>@Omatter.Name_Matter</td>
                    <td>@Omatter.Schedule</td>
                    <td><a class="btn btn-primary" href="~/Teacher/ViewTeacher/@Omatter.Teacher">Ver Profesor</a></td>
                    <td>@Omatter.Quota</td>
                    <td>
                        @if (User.Identity.IsAuthenticated)
                        {
                            string Usuario = User.Identity.Name;
                            if (Usuario == "Administrador")
                            {
                                <a class="btn btn-default" href="~/Matter/Edit/@Omatter.Id">Editar</a>
                                <a class="btn btn-danger" href="~/Matter/Delete/@Omatter.Id">Eliminar</a>
                            }
                            else
                            {
                                <a class="btn btn-success" href="~/Inscription/Inscription/@Omatter.Id">Inscribirse</a>
                            }
                        }
                    </td>
                </tr>
            }
        </table>
    </div>
</div>

AlkemyChallenge/Views/Matter/New.cshtml
@model AlkemyChallenge.Models.ViewModels.DataMatters
@{
    ViewBag.Title = "Nuevo";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("New", "Matter", FormMethod.Post))
{
    string Usuario = User.Identity.Name;
    if (Usuario == "Administrador")
    {
        <div class="row">
            <div class="col-md-12">
                <div>
                    @Html.LabelFor(m => m.Name_Matter)
                    @Html.TextBoxFor(m => m.Name_Matter, "", new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Name_Matter, null)
                </div>
                <div>
                    @Html.LabelFor(m => m.Schedule)<br />
                    @Html.EditorFor(m => m.Schedule, "", new { @class = "form-control" })<br />
                    @Html.ValidationMessageFor(m => m.Schedule, null)
                </div>
                <div>
                    @Html.LabelFor(m => m.Id_Teacher)
                    @Html.TextBoxFor(m => m.Id_Teacher, "", new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Id_Teacher, null)
                </div>
                <div>
                    @Html.LabelFor(m => m.Quota)
                    @Html.TextBoxFor(m => m.Quota, "", new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Quota, null)
                </div>

                <div style="text-align:right">
                    <input value="Guardar" class="btn btn-success" type="Submit" />
                </div>
            </div>
        </div>
    }
    else
    {
        <label> NO TIENE LOS PERMISOS NECESARIOS</label>
        <a class="btn btn-danger" href="~/Matter">Volver</a>

    }
}