AlkemyChallenge/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AlkemyChallenge;
using AlkemyChallenge.Models;
using AlkemyChallenge.Models.ViewModels;

namespace Alkemy.Controllers
{
    [Authorize]
    public class TeacherController : Controller
    {
        // GET: Teacher
        public ActionResult Index(string message = "")
        {
            List<ListTeacher> List;
            using (UniversityEntities DB = new UniversityEntities())
            {

                List = (from t in DB.Teachers
                        select new ListTeacher
                        {
                            Id = t.Id,
                            First_Name = t.First_Name,
                            Last_Name = t.Last_Name,
                            DNI = t.DNI,
                            File_Teacher = t.File_Teacher,
                            Active=t.Active
                        }).ToList();
            }
            ViewBag.Message = message;
            return View(List);
        }
        public ActionResult New()
        {
            return View();
        }

        [HttpPost]
        public ActionResult New(DataTeacher NewT)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (UniversityEntities DB = new UniversityEntities())
                    {
                        var NTeacher = new Teachers();
                        NTeacher.First_Name = NewT.First_Name;
                        NTeacher.Last_Name = NewT.Last_Name;
                        NTeacher.DNI = NewT.DNI;
                        NTeacher.File_Teacher = NewT.File_Teacher;

                        DB.Teachers.Add(NTeacher);
                        DB.SaveChanges();
                    }
                    return Redirect("/Teacher");
                }
                return View(NewT);
            }
            catch (Exception ex)
            {

                throw new Exception(ex.Message);
            }
        }
        public ActionResult Edit(int Id)
        {
            DataTeacher ETeachers = new DataTeacher();
            using (UniversityEntities DB = new UniversityEntities())
            {
                var ETeacher = DB.Teachers.Find(Id);
                ETeachers.First_Name = ETeacher.First_Name;
                ETeachers.Last_Name = ETeacher.Last_Name;
                ETeachers.DNI = ETeacher.DNI;
                ETeachers.File_Teacher = ETeacher.File_Teacher;
                ETeachers.Id = ETeacher.Id;
            }
            return View(ETeachers);
        }
        [HttpPost]
        public ActionResult Edit(DataTeacher ETeachers)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (UniversityEntities DB = new UniversityEntities())
                    {
                        var ETeacher = DB.Teachers.Find(ETeachers.Id);
                        ETeacher.Id = ETeachers.Id;
                        ETeacher.First_Name = ETeachers.First_Name;
                        ETeacher.Last_Name = ETeachers.Last_Name;
                        ETeacher.DNI = ETeachers.DNI;
                        ETeacher.File_Teacher = ETeachers.File_Teacher;

                        DB.Entry(ETeacher).State = System.Data.Entity.EntityState.Modified;
                        DB.SaveChanges();
                    }
                    return Redirect("/Teacher");
                }
                return View(ETeachers);
            }
            catch (Exception ex)
            {

                throw new Exception(ex.Message);
            }
        }

        [HttpGet]
        public ActionResult Delete(int Id)
        {
            using (UniversityEntities DB = new UniversityEntities())
            {
                var DTeacher = DB.Teachers.Find(Id);
                var IDuplicated = DB.Matters.ToList();
                foreach (var dato in IDuplicated)
                {
                    if (dato.Id_Teacher == Id)
                    {
                        return RedirectToAction("Index", new { message = "No se pudo eliminar ya que el Profesor tiene materias a su cargo" });
                    }
                }
                DB.Teachers.Remove(DTeacher);
                DB.SaveChanges();
            }
            return Redirect("/Teacher");
        }
        public ActionResult ViewTeacher(int id)
        {
            List<ListTeacher> List;
            using (UniversityEntities DB = new UniversityEntities())
            {
                List = (from t in DB.Teachers
                        select new ListTeacher
                        {
                            Id = t.Id,
                            First_Name = t.First_Name,
                            Last_Name = t.Last_Name,
                            DNI = t.DNI,
                            File_Teacher = t.File_Teacher,
                            Active = t.Active
                        }).ToList();

                foreach (var dato in List)
                {
                    if (dato.Id == id)
                    {
                        List<ListTeacher> TeacherId = new List<ListTeacher>();
                        TeacherId.Add(new ListTeacher() { Id = id, First_Name = dato.First_Name, Last_Name = dato.Last_Name, DNI = dato.DNI, File_Teacher = dato.File_Teacher });
                        return View(TeacherId);
                    }
                }
            }
            return View(List);
        }
           
        public ActionResult Active(int Id)
        {
            using (UniversityEntities DB = new UniversityEntities())
            {

                var DTeacher = DB.Teachers.Find(Id);
                if (!DTeacher.Active)
                {
                    DTeacher.Active = true;
                }
                else
                {
                    DTeacher.Active = false;
                }
                DB.Entry(DTeacher).State = System.Data.Entity.EntityState.Modified;
                DB.SaveChanges();
            }
            return Redirect("/Teacher");
        }
    }
}

AlkemyChallenge/Views/Teacher/Edit.cshtml
@model AlkemyChallenge.Models.ViewModels.DataTeacher
@{
    ViewBag.Title = "Editar";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Edit", "Teacher", FormMethod.Post))
{
    string Usuario = User.Identity.Name;
    if (Usuario == "Administrador")
    {
        <div class="row">
            <div class="col-md-12">
                <div>
                    @Html.LabelFor(d => d.First_Name)
                    @Html.TextBoxFor(d => d.First_Name, "", new { @class = "form-control" })
                    @Html.ValidationMessageFor(d => d.First_Name, null)
                </div>
                <div>
                    @Html.LabelFor(d => d.Last_Name)
                    @Html.TextBoxFor(d => d.Last_Name, "", new { @class = "form-control" })
                    @Html.ValidationMessageFor(d => d.Last_Name, null)
                </div>
                <div>
                    @Html.LabelFor(d => d.DNI)
                    @Html.TextBoxFor(d => d.DNI, "", new { @class = "form-control" })
                    @Html.ValidationMessageFor(d => d.DNI, null)
                </div>
                <div>
                    @Html.LabelFor(d => d.File_Teacher)
                    @Html.TextBoxFor(d => d.File_Teacher, "", new { @class = "form-control" })
                    @Html.ValidationMessageFor(d => d.File_Teacher, null)
                </div>
                <div style="text-align:right">
                    <input value="Guardar" class="btn btn-success" type="Submit" />
                </div>
            </div>
        </div>
    }
    else
    {
        <label> NO TIENE LOS PERMISOS NECESARIOS</label>
        <a class="btn btn-danger" href="~/Matter">Volver</a>

    }
}

AlkemyChallenge/Views/Teacher/Index.cshtml
@model List<AlkemyChallenge.Models.ViewModels.ListTeacher>
@{
    string Usuario = User.Identity.Name;
    if (Usuario == "Administrador")
    {
        ViewBag.Title = "Lista Profesores";


        <h2>@ViewBag.Title</h2>
        <div class="row" style="text-align:right;padding:5px">
            <a href="~/Teacher/New" class="btn btn-success">Nuevo Profesor</a>

        </div>
        <div class="container">
            @{
                if (!string.IsNullOrEmpty(ViewBag.Message))
                {
                    <div class="alert alert-danger">@ViewBag.Message</div>
                }
            }
        </div>
        <div class="row">
            <div class="col-md-12">
                <table class="table">
                    <tr>
                        <th>Id_Teacher</th>
                        <th>Nombre</th>
                        <th>Apellido</th>
                        <th>DNI</th>
                        <th>Legajo</th>
                        <th>Activo</th>
                        <th></th>
                    </tr>
                    @foreach (var Oteacher in Model)
                    {
                <tr>
                    <td>@Oteacher.Id</td>
                    <td>@Oteacher.First_Name</td>
                    <td>@Oteacher.Last_Name</td>
                    <td>@Oteacher.DNI</td>
                    <td>@Oteacher.File_Teacher</td>
                    <td>@Oteacher.Active</td>
                    <td>
                        <a class="btn btn-default" href="~/Teacher/Edit/@Oteacher.Id">Editar</a>
                        <a class="btn btn-danger" href="~/Teacher/Delete/@Oteacher.Id">Eliminar</a>
                        <a class="btn btn-warning" href="~/Teacher/Active/@Oteacher.Id">Activar/Desactivar</a>
                    </td>
                </tr>

        }
                </table>
            </div>
        </div>
    }
    else
    {
        <label> NO TIENE LOS PERMISOS NECESARIOS</label>
        <a class="btn btn-danger" href="~/Matter">Volver</a>

    }
}

AlkemyChallenge/Views/Teacher/New.cshtml
@model AlkemyChallenge.Models.ViewModels.DataTeacher
@{

    ViewBag.Title = "Nuevo";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("New", "Teacher", FormMethod.Post))
{
    string Usuario = User.Identity.Name;
    if (Usuario == "Administrador")
    {
        <div class="row">
            <div class="col-md-12">
                <div>
                    @Html.LabelFor(d => d.First_Name)
                    @Html.TextBoxFor(d => d.First_Name, "", new { @class = "form-control" })
                    @Html.ValidationMessageFor(d => d.First_Name, null)
                </div>
                <div>
                    @Html.LabelFor(d => d.Last_Name)
                    @Html.TextBoxFor(d => d.Last_Name, "", new { @class = "form-control" })
                    @Html.ValidationMessageFor(d => d.Last_Name, null)
                </div>
                <div>
                    @Html.LabelFor(d => d.DNI)
                    @Html.TextBoxFor(d => d.DNI, "", new { @class = "form-control" })
                    @Html.ValidationMessageFor(d => d.DNI, null)
                </div>
                <div>
                    @Html.LabelFor(d => d.File_Teacher)
                    @Html.TextBoxFor(d => d.File_Teacher, "", new { @class = "form-control" })
                    @Html.ValidationMessageFor(d => d.File_Teacher, null)
                </div>

                <div style="text-align:right">
                    <input value="Guardar" class="btn btn-success" type="Submit" />
                </div>
            </div>
        </div>
    }
    else
    {
        <label> NO TIENE LOS PERMISOS NECESARIOS</label>
        <a class="btn btn-danger" href="~/Matter">Volver</a>

    }
}

AlkemyChallenge/Views/Teacher/ViewTeacher.cshtml
@model List<AlkemyChallenge.Models.ViewModels.ListTeacher>
@{
    ViewBag.Title = "Informacion Profesor";
}

<h2>@ViewBag.Title</h2>
        <div class="row" style="text-align:right;padding:5px">

        </div>
        <div class="row">
            <div class="col-md-12">
                <table class="table">
                    <tr>
                        <th>Nombre</th>
                        <th>Apellido</th>
                        <th>DNI</th>
                        <th></th>
                    </tr>
                    @foreach (var Oteacher in Model)
                    {
                        <tr>
                            <td>@Oteacher.First_Name</td>
                            <td>@Oteacher.Last_Name</td>
                            <td>@Oteacher.DNI</td>
                        </tr>
                    }
                </table>
          </div>
        </div>